apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- configmap.yaml
# ingress는 각 overlay에서 환경별로 정의 (EKS: ALB, dev: nginx)
