apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-kafka
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-zookeeper
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-kafka-ui
automountServiceAccountToken: false
